### ISSUE TITLE
Pupeteer Error - Evaluation failed: Error: Element is not a <select> element.

### ISSUE THREAD

**Issue by asegretto** [starsprung/amazon-ynab-sync#31]
I was able to sync on 05/22/2022 but today I get the same error on multiple installations (multiple computers).

Error: Evaluation failed: Error: Element is not a <select> element.
    at <anonymous>:3:23
    at ExecutionContext._evaluateInternal (/home/MYUSERNAME/.nvm/versions/node/v16.15.1/lib/node_modules/amazon-ynab-sync/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/MYUSERNAME/.nvm/versions/node/v16.15.1/lib/node_modules/amazon-ynab-sync/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async ElementHandle.evaluate (/home/MYUSERNAME/.nvm/versions/node/v16.15.1/lib/node_modules/amazon-ynab-sync/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:102:16)
    at async DOMWorld.select (/home/MYUSERNAME/.nvm/versions/node/v16.15.1/lib/node_modules/amazon-ynab-sync/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:295:24)
    at async AmazonOrderReportsApi._fillReportForm (/home/MYUSERNAME/.nvm/versions/node/v16.15.1/lib/node_modules/amazon-ynab-sync/node_modules/amazon-order-reports-api/lib/index.js:232:9)
    at async AmazonOrderReportsApi._getReport (/home/MYUSERNAME/.nvm/versions/node/v16.15.1/lib/node_modules/amazon-ynab-sync/node_modules/amazon-order-reports-api/lib/index.js:267:28)
    at async AmazonOrderReportsApi.getItems (/home/MYUSERNAME/.nvm/versions/node/v16.15.1/lib/node_modules/amazon-ynab-sync/node_modules/amazon-order-reports-api/lib/index.js:124:9)
    at async Object.getAmazonTransactions (/home/MYUSERNAME/.nvm/versions/node/v16.15.1/lib/node_modules/amazon-ynab-sync/lib/amazon.js:72:26)
    at async Object.batch [as default] (/home/MYUSERNAME/.nvm/versions/node/v16.15.1/lib/node_modules/amazon-ynab-sync/node_modules/it-batch/index.js:20:20)

**Comment by sandhawke** [comment]
Me too. Looks like amazon changed the https://amazon.com/b2b/reports page a bit.
